name: release-ios-testflight

# This workflow builds, archives, exports, validates and uploads your ios app.
# The version from input is only used for artifact names and as the release to upload the final ipa to.
# Bump the versions in `mobile/ios-src/Info.plist` to change the version of your app bundle.

# Special setup and Apple Developer Program membership (99$/year) is required for this workflow!

# For setup instructions, see https://www.nikl.me/blog/2023/github_workflow_to_publish_ios_app/

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version - in the form of v1.2.3'
        required: true
        type: string

# ToDo: adapt names
env:
  # used for uploading the app to a GitHub release
  GAME_EXECUTABLE_NAME: bevy_game
  XCODE_PROJECT: mobile
  MOBILE_DIRECTORY: mobile

permissions:
  contents: write
